sudo: required
services:
  - docker

before_install:
  - docker build -t sebastiansloniec/react-test -f client/Dockerfile.dev ./client

script:
  # - docker run sebastiansloniec/react-test npm test -- --coverage # To exit test
  - docker run -e CI=true sebastiansloniec/react-test npm test

# Build prod versions and push them to dockerhub
after_success:
  - docker build -t sebastiansloniec/multi-client ./client
  - docker build -t sebastiansloniec/multi-nginx ./nginx
  - docker build -t sebastiansloniec/multi-server ./server
  - docker build -t sebastiansloniec/multi-worker ./worker
  # Login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sebastiansloniec/multi-client
  - docker push sebastiansloniec/multi-nginx
  - docker push sebastiansloniec/multi-server
  - docker push sebastiansloniec/multi-worker
